let phrases_bronze = [
    "kys",
    "Bronze",
    "idiot",
    "just a game",
    "u mad?",
    "blind",
    "kid",
    "retard",
    "easy",
    "uninstall",
    "Report",
    "your mom",
    "afk",
    "Noob",
    "cry",
    "suck",
    "****",
    "troll"
];

let phrases_mariokart = [
    "Use a mushroom",
    "Miss an itembox",
    "Hit by a red shell",
    "Fell of the track",
    "Hit a banana",
    "Loose to a com",
    "Avoid a red shell",
    "Launch a blue shell",
    "Finish in first",
    "Hit by a green shell",
    "Drive off the track",
    "Hit a cow",
    "Hit a bat",
    "Start boost failed",
    "Hit someone with a green shell",
    "Hit by your own shell",
    "Perfect Power Slide",
    "Finish in last place",
    "Use a shortcut"
]